version: 2
updates:
- package-ecosystem: npm
  directory: "/src/client"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/server/ASTViewer"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  allow:
    - dependency-name: "Fantomas.FCS"
- package-ecosystem: nuget
  directory: "/src/server/FantomasOnlineV6"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  allow:
    - dependency-name: "Fantomas.Core"